# Docker Compose - NGINX, PHP7, PostgreSQL

version: '2'

services:

#  php:
#    build: ./docker/php7-fpm
#    volumes:
#      - ./website/:/var/www/app
#      - ./logs/app1:/var/www/app/logs

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
      - "8443:443"
#    volumes_from:
#      - php
    volumes:
      - ./logs/nginx:/var/log/nginx
